# Generated by Django 4.1.4 on 2023-03-27 23:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionDocente', '0020_rename_periodo_dos_competencia_indicadores_desempeño_periodo_dos_logro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historico',
            name='Estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Club',
            field=models.IntegerField(blank=True, choices=[(1, 'Primaria'), (2, 'COCOMA'), (3, 'ROBOTICA'), (4, 'DANZAS'), (5, 'ONU'), (6, 'INGLES'), (7, 'FRANCES'), (8, 'DEPORTES'), (9, 'CIENCIA CON CONCIENCIA'), (10, 'PERIODISMO'), (11, 'No Aplica')], null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Numero_documento',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='historico',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDocente.estudiante'),
        ),
        migrations.AddField(
            model_name='historico',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDocente.curso'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Apellido',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Nombre',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Patologia_alergias',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Restaurante',
            field=models.IntegerField(blank=True, choices=[(1, 'No'), (2, 'Medio'), (3, 'Completo')], null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Ruta',
            field=models.IntegerField(blank=True, choices=[(1, 'No'), (2, 'Media'), (3, 'Completa')], null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Telefono_Acudiente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historico',
            name='Profesor',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='psicoorientacion',
            name='Evidencias',
            field=models.ImageField(blank=True, null=True, upload_to='PSICOLOGIA'),
        ),
        migrations.AlterField(
            model_name='psicoorientacion',
            name='Proxima_cita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='psicoorientacion',
            name='psicoorientador',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Convivencia',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDocente.estudiante'),
        ),
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionDocente.curso'),
        ),
        migrations.AddField(
            model_name='branch',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocente.college'),
        ),
    ]
